
name: supabase-lint
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo placeholder
        run: echo "Add Supabase CLI and migration checks here"
